server:
  port: 10002
spring:
  application:
    name: ribbon-consumer
#providers这个是自己命名的，ribbon,listOfServer这两个是规定的
providers:
  ribbon:
    listOfServers: localhost:8080,localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/